package com.myteam.driverdepartmenttrafficviolations;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Driver Record")
public class DriverRecord implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Driver ID")
	private java.lang.String driverId;
	@org.kie.api.definition.type.Label("Driver Name")
	private java.lang.String driverName;
	@org.kie.api.definition.type.Label("Points Total")
	private java.lang.Integer pointsTotal;

	public DriverRecord() {
	}

	public java.lang.String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(java.lang.String driverId) {
		this.driverId = driverId;
	}

	public java.lang.String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(java.lang.String driverName) {
		this.driverName = driverName;
	}

	public java.lang.Integer getPointsTotal() {
		return this.pointsTotal;
	}

	public void setPointsTotal(java.lang.Integer pointsTotal) {
		this.pointsTotal = pointsTotal;
	}

	public DriverRecord(java.lang.String driverId, java.lang.String driverName,
			java.lang.Integer pointsTotal) {
		this.driverId = driverId;
		this.driverName = driverName;
		this.pointsTotal = pointsTotal;
	}

}