package com.myteam.driverdepartmenttrafficviolations;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Violation")
public class Violation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Violation Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("Violation State")
	private java.lang.String state;

	@org.kie.api.definition.type.Label("Driver ID")
	private java.lang.String driverId;

	@org.kie.api.definition.type.Label("Violation ID")
	private java.lang.String violationId;

	@org.kie.api.definition.type.Label(value = "Speed")
	private java.lang.Double speed;

	public Violation() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(java.lang.String driverId) {
		this.driverId = driverId;
	}

	public java.lang.String getViolationId() {
		return this.violationId;
	}

	public void setViolationId(java.lang.String violationId) {
		this.violationId = violationId;
	}

	public java.lang.Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(java.lang.Double speed) {
		this.speed = speed;
	}

	public Violation(java.lang.String type, java.lang.String state,
			java.lang.String driverId, java.lang.String violationId,
			java.lang.Double speed) {
		this.type = type;
		this.state = state;
		this.driverId = driverId;
		this.violationId = violationId;
		this.speed = speed;
	}

}