package com.myteam.driverdepartmenttrafficviolations;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Violation Report")
public class ViolationReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Driver ID")
	private java.lang.String driverId;
	@org.kie.api.definition.type.Label("Points")
	private java.lang.Integer points;
	@org.kie.api.definition.type.Label("Fine Debt")
	private java.lang.Double fineDebt;

	public ViolationReport() {
	}

	public java.lang.String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(java.lang.String driverId) {
		this.driverId = driverId;
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public java.lang.Double getFineDebt() {
		return this.fineDebt;
	}

	public void setFineDebt(java.lang.Double fineDebt) {
		this.fineDebt = fineDebt;
	}

	public ViolationReport(java.lang.String driverId, java.lang.Integer points,
			java.lang.Double fineDebt) {
		this.driverId = driverId;
		this.points = points;
		this.fineDebt = fineDebt;
	}

}