package org.jboss.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Mortgage Application")
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Years of amortization for loan")
	private java.lang.Integer amortization;
	@org.kie.api.definition.type.Label(value = "Applicant")
	private org.jboss.example.Applicant applicant;
	@org.kie.api.definition.type.Label(value = "Down Payment")
	private java.lang.Integer downpayment;
	@org.kie.api.definition.type.Label(value = "Error details")
	private org.jboss.example.ValidationErrorDO errors;
	@org.kie.api.definition.type.Label(value = "Mortgage loan amount requested")
	private java.lang.Integer mortgageamount;
	@org.kie.api.definition.type.Label(value = "Property Details")
	private org.jboss.example.Property property;

	public Application() {
	}

	public java.lang.Integer getAmortization() {
		return this.amortization;
	}

	public void setAmortization(java.lang.Integer amortization) {
		this.amortization = amortization;
	}

	public org.jboss.example.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(org.jboss.example.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public org.jboss.example.ValidationErrorDO getErrors() {
		return this.errors;
	}

	public void setErrors(org.jboss.example.ValidationErrorDO errors) {
		this.errors = errors;
	}

	public java.lang.Integer getMortgageamount() {
		return this.mortgageamount;
	}

	public void setMortgageamount(java.lang.Integer mortgageamount) {
		this.mortgageamount = mortgageamount;
	}

	public org.jboss.example.Property getProperty() {
		return this.property;
	}

	public void setProperty(org.jboss.example.Property property) {
		this.property = property;
	}

	public Application(java.lang.Integer amortization,
			org.jboss.example.Applicant applicant,
			java.lang.Integer downpayment,
			org.jboss.example.ValidationErrorDO errors,
			java.lang.Integer mortgageamount,
			org.jboss.example.Property property) {
		this.amortization = amortization;
		this.applicant = applicant;
		this.downpayment = downpayment;
		this.errors = errors;
		this.mortgageamount = mortgageamount;
		this.property = property;
	}

}